#!/bin/bash
python -m venv env
env/bin/pip install --upgrade pip setuptools
env/bin/pip install -r requirements.txt
source env/bin/activate
cd server
export FLASK_APP=server.py
export FLASK_ENV=development
python -m flask run